### ISSUE TITLE
Invalid balance shown for satoshi era address: 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa

### ISSUE THREAD

**Issue by simlarsen** [mempool/mempool#2047] opened 2022-07-08 19:19 UTC
### Description

Invalid balance is shown for this address `1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa` on mempool.space. It shows the wallet has   ‎18.53501873 BTC when in fact it has 68.54501873 BTC

### Screenshots

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/104437376/178056820-105d1533-40a6-4234-9e9a-c9c41c2b4400.png">

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/104437376/178056846-26227aa7-65fd-4783-81ea-40d8a8b08db1.png">

**Comment by katesalazar** [comment] 2022-07-08 20:40
probable duplicate of ticket 1075

**Comment by antonilol** [comment] 2022-07-10 06:29
> probable duplicate of ticket 1075

Not duplicate, this issue is a bug report and mine is a feature request

I think that your other block explorer shows P2PK as P2PKH to give the user addresses and not a long hex string. So the values are from two scripts added together and mempool.space only shows the P2PKH addresses

**Comment by junderw** [comment] 2022-07-29 13:31
Fun fact: the first utxo in block 0 is unspendable, even with Satoshi's private key.

**Closed** 2022-07-29 13:41 UTC
