### ISSUE TITLE
Upper bound of feerate range should maybe show effective feerate

### ISSUE THREAD

**Issue by Xekyo** [mempool/mempool#360] opened 2021-02-24 13:36 UTC
### Description

[Two](https://twitter.com/ksedgwic/status/1364356751001149441) people [asked](https://twitter.com/flying_dude/status/1364550229715013635) about this on Twitter in the past 24h:

![image](https://user-images.githubusercontent.com/4060799/109005847-6bb35500-7678-11eb-8f41-0efa0c8fa5ab.png)

The preview of the next block states that the next block will include transactions of the feerates 88–8,428 sat/vB.

The transaction with the highest feerate in the mempool is https://blockchair.com/bitcoin/transaction/337de3cdcf0c0a9527bc4e7c8577afe31bcecd4d54ee72f07283476ce7dabe8a, which does indeed pay 8,428 sat/vB. However, this is actually a 110 vB CPFP transaction trying to bump an 82 kvB parent transaction that paid 10 sat/vB. In result, the effective feerate for the former transaction is that of its ancestor set, i.e. 21.38 sat/vB for the two transactions together.

### Expected behaviour

I was wondering whether it might make sense to present the future blocks' feerate ranges in effective feerates rather than in absolute feerates. I realize that this may be non-trivial, though.

This could potentially be achieved by running `getblocktemplate` for the next block, and using the transaction package feerates of the transactions in the block. Since dependent transactions need to be sorted in topological order in the block, transaction packages may be efficiently discoverable in a linear pass. The subsequent block's upper bound could then perhaps be inductively calculated from the prior subsequent block's lower bound.

### Notes

TBH, not sure if this is worth the effort, or whether this would even be a good way to approach it. I just wanted to put it out there because the feerate range seems to raise questions among users.

**Comment by wiz** [comment] 2021-02-24 13:56
Yes, this is a known issue, mempool currently does not calculate the net average fee rate for an unconfirmed chain of mempool transactions. It's on our roadmap to add the CPFP calculations coming soon...

**Comment by wiz** [comment] 2021-02-24 13:58
Duplicate of #353

**Comment by wiz** [comment] 2021-02-24 14:25
Oops closed this by mistake, re-opening

**Closed** 2021-03-18 16:47 UTC
