### ISSUE TITLE
Human readable x-Axis date labels.

### ISSUE THREAD

**Issue by MiguelMedeiros** [mempool/mempool#899] opened 2021-11-01 21:56 UTC
### Description
Make echarts human readable x-Axis date labels.

### Expected Behaviour
2 hours chart: **15 mins interval**
![2h-span](https://user-images.githubusercontent.com/5798170/138341985-9a914aec-f7c2-4358-b1ac-b5aa4a1e7aee.jpg)

24 hours chart: **2 hours interval**
![24h-span](https://user-images.githubusercontent.com/5798170/138341987-5ffc9df2-5509-4137-a701-f44f215decef.jpg)

1 week chart: **1 day interval**
![1w-span](https://user-images.githubusercontent.com/5798170/138341983-f582c54a-c227-413e-8a5b-eafd59b86b22.jpg)

1 month chart: **1 week interval**
![1m-span](https://user-images.githubusercontent.com/5798170/138342589-7b835c63-8d95-4532-9da3-6da6700d21eb.jpg)

3 months chart: **1 week interval**
![3m-span](https://user-images.githubusercontent.com/5798170/138341981-4850a958-0f95-4a3a-92fb-1e2e355e5ec0.jpg)

6 months chart: **1 month interval**
![6m-span](https://user-images.githubusercontent.com/5798170/138341980-76894091-bab2-45a9-9848-8619c7663682.jpg)

1 year chart: **1 month interval**
![1y-span](https://user-images.githubusercontent.com/5798170/138341978-bf31cb95-0de7-49ae-90a2-618987bdb753.jpg)

**Comment by wiz** [comment] 2021-11-19 22:47
Duplicate of #842

**Closed by wiz** 2021-11-19 22:47 UTC
Labels: bug
