### ISSUE TITLE
Add block health to mining pool page

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#3032] opened 2023-02-11 08:10 UTC
Just like the [blocks](https://mempool.space/blocks) page, the [mining pool page](https://mempool.space/mining/pool/antpool) should display the block health data.

Consider replacing the "reward" column with Health to make it fit.

**Comment by wiz** [comment] 2023-02-20 07:58
Duplicate of #3027

**Closed by wiz** 2023-02-20 07:58 UTC
