### ISSUE TITLE
Unfurler: normalize and define CSS styles

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#2781] opened 2022-12-03 16:23 UTC
Different environments now have different styling for the `Unknown` miner tag. 

We should define what the expected style should be so we can add regression tests for the previews:

![tk7](https://user-images.githubusercontent.com/100320/205450921-1ecf80a3-2a3f-4a37-abcb-5e91acf6fbdc.png)
![fra](https://user-images.githubusercontent.com/100320/205450922-9c54c2d6-1c53-44df-8435-7c85bb18ce86.png)
![prod](https://user-images.githubusercontent.com/100320/205450923-150c7923-8bec-44db-bc3d-24b2a694e505.png)

**Comment by mononaut** [comment] 2022-12-07 21:37
Expected style is the smaller font tag, with a gray background.

The inconsistent color was caused by a stray css transition, which meant the unfurler could capture the image at any point from default blue to unknown gray, depending how fast everything else loaded.

That should be fixed in #2809.

I can't explain why the tag would have ever rendered in a larger font, and haven't been able to reproduce that yet.

**Closed** 2022-12-26 11:29 UTC
Labels: bug, UI/UX
