### ISSUE TITLE
Witness Disassembly

### ISSUE THREAD

**Issue by casey** [mempool/mempool#2641] opened 2022-10-15 01:15 UTC
When viewing a transaction it would be awesome if witnesses, in addition to being displayed as raw hex, displayed in a disassembled, human-readable format. I've been working on constructing taproot transactions, and it would be very helpful to be able to examine some on-chain transactions to see what's in there.

For example, [this transaction](https://mempool.space/tx/905ecdf95a84804b192f4dc221cfed4d77959b81ed66013a7e41a6e61e7ed530) is, according to [this stackoverflow post](https://bitcoin.stackexchange.com/a/111003/3750), the first scriptpath 2-of-2 multisig spend on mainnet. However, the witness is rendered as just the witness elements in hex:

```
23b1d4ff27b16af4b0fcb9672df671701a1a7f5a6bb7352b051f461edbc614aa6068b3e5313a174f90f3d95dc4e06f69bebd9cf5a3098fde034b01e69e8e788901 0fd4a0d3f36a1f1074cb15838a48f572dc18d412d0f0f0fc1eeda9fa4820c942abb77e4d1a3c2b99ccf4ad29d9189e6e04a017fe611748464449f681bc38cf39 20febe583fa77e49089f89b78fa8c116710715d6e40cc5f5a075ef1681550dd3c4ad20d0fa46cb883e940ac3dc5421f05b03859972639f51ed2eccbf3dc5a62e2e1b15ac c02e44c9e47eaeb4bb313adecd11012dfad435cd72ce71f525329f24d75c5b9432774e148e9209baf3f1656a46986d5f38ddf4e20912c6ac28f48d6bf747469fb1
```

It would be awesome if it was parsed, including parsing the tapscript into assembly, the control block into the merkle path, etc, and displayed on the transaction details page.

**Comment by softsimon** [comment] 2022-10-17 13:23
Note that we already support this in our backend when using Bitcoin Core. See screen shot below.

The issue is with `blockstream/esplora` that doesn't do the parsing of taproot scripts. Maybe something for @junderw to look into?

<img width="599" alt="Screen Shot 2022-10-17 at 17 22 00" src="https://user-images.githubusercontent.com/8561090/196188142-800114ab-df48-445b-afe2-b2779cd86586.png">

**Comment by junderw** [comment] 2022-10-17 15:55
Finally found the issue.

**Comment by softsimon** [comment] 2023-07-13 06:29
Fixed in https://github.com/mempool/electrs/pull/2

**Closed by softsimon** 2023-07-13 06:29 UTC
Labels: enhancement
