### ISSUE TITLE
Tx fee ranges not display accurately

### ISSUE THREAD

**Issue by Sanksari12** [mempool/mempool#1227] opened 2022-02-06 11:56 UTC
### Description

In the main view mined blocks show a range of tx fees of the txs included in the block. Unit is in sat/vB for example 2-454sat/vB for block 722043. 
This makes it look as if no 1sat/vB transactions are included in the block, which is not the case. 

#### Version

v2.3.1

### Steps to reproduce

Open the mempool.space main view and select a random block with a displayed fee rate from 2 - n sat/vB. Click on the mined block and skip to the last page of included txs

### Expected behaviour

On the last page of included transactions (sorted by descending tx fee per vB) in the selected block it shows txs with 1sat/vB or 1.02sat/vB are included. I would expect the fee range on the block to be shown as 1 - n sat/vB

### Actual behaviour

The block is shown as including only 2 - n sat/vB transactions making it look like 1sat/vB txs are not included in blocks by miners even though blocks are not filled completely. This could be pushing users to select higher fees for their transactions.

### Screenshots
![mempool](https://user-images.githubusercontent.com/73398276/152679658-e8329875-d780-45d4-9de7-5a9937245b0a.png)

#### Device or machine

Desktop and mobile browsers were tested.

**Comment by nymkappa** [comment] 2022-02-06 13:38
Maybe you'll find your answer here :) https://github.com/mempool/mempool/issues/101

**Comment by wiz** [comment] 2022-02-08 01:57
Closing as duplicate of #101

**Closed by wiz** 2022-02-08 01:57 UTC
