### ISSUE TITLE
Store historical USD prices

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1389] opened 2022-03-17 11:23 UTC
- [ ] Find historical USD price data API to store in the blocks table when blocks are indexed
- [ ] When new blocks comes in, store the current BTC/USD price
- [ ] When viewing an old block or a transaction. Use the stored USD price for that block to display the block reward and transferred value in USD
- [ ] Create a new graph that show the historical USD reward for all blocks.

**Comment by wiz** [comment] 2022-06-07 15:25
Duplicate of #176

**Closed by wiz** 2022-06-07 15:25 UTC
