### ISSUE TITLE
This transaction looks buggy, Invalid or display bug?

### ISSUE THREAD

**Issue by Transisto** [mempool/mempool#3764] opened 2023-05-12 14:32 UTC
1. It cannot be a multisig of any kind if it's a legacy address type.
2. UNKNOWN ?
3. It shows an effective fee of 71 but hasn't confirmed into blocks with a lower average.

![image](https://github.com/mempool/mempool/assets/388716/c48fd39e-1adf-4fce-8695-519e45250a9e)

https://mempool.space/tx/26041fc6906080c8ed4c44aafee361415064777c0f5176bed0aada4d501b5fc5

**Comment by mononaut** [comment] 2023-05-12 14:58
Looks fine to me.

These are "bare multisig" outputs, locked by a 1-of-3 `OP_CHECKMULTISIG` script directly in the scriptSig:
<img width="531" alt="Screenshot 2023-05-12 at 8 39 01 AM" src="https://github.com/mempool/mempool/assets/83316221/b8273ee3-49aa-4c13-89ad-79dc990c2e48">

Bare multisigs are uncommon now, but still standard up to n-of-3. They are sometimes used to embed arbitrary data in the blockchain for the Counterparty protocol - this particular transaction is an example of a "Bitcoin Stamp" which uses the multisig outputs to encode a small image.

Unlike the various types of pay-to-script-hash multisigs, this kind of output does not have a defined address format, so there's nothing to display in the address field.

Perhaps it would be more helpful to display "Bare Multisig" or "P2MS" instead of "UNKNOWN" there? We currently display "P2PK" for [pay-to-pub-key outputs](https://mempool.space/tx/f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16#vout=1), which also lack a defined address format.

**Comment by mononaut** [comment] 2023-05-12 15:06
> 3. It shows an effective fee of 71 but hasn't confirmed into blocks with a lower average.

The reason the transaction hasn't confirmed despite an apparently competitive fee is because the large number of bare multisig outputs uses a disproportionate share of the block SIGOP limit.

This causes Bitcoin Core treat it as if it had a higher vsize (and so lower effective fee rate and mining priority).

We don't account for this rule yet, and so only display the un-adjusted rate. (see #3658)

**Comment by softsimon** [comment] 2023-05-13 22:25
[blockstream/electrs](https://github.com/Blockstream/electrs) lacks the `MULTISIG` output type, and displays `UNKNOWN` instead.

**Comment by softsimon** [comment] 2023-07-17 05:50
Fixed in https://github.com/mempool/electrs/pull/9

**Closed by softsimon** 2023-07-17 05:50 UTC
