### ISSUE TITLE
Fiat value is assigned to Testnet/signet

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#4602] opened 2024-01-22 17:42 UTC
<img width="423" alt="Screenshot 2024-01-23 at 00 41 55" src="https://github.com/mempool/mempool/assets/8561090/66d702c3-bd34-4dcb-9f5f-2bb731bef1e1">

**Comment by Muniru0** [comment] 2024-03-01 06:51
@softsimon Please can you provide more context here.

**Comment by natsoni** [comment] 2024-03-01 10:20
To add context, the bug happens when changing network in-app from mainnet to testnet/signet, and is fixed with a CTRL+R. It does not happen when directly opening testnet/signet (opening https://mempool.space/testnet/block/000000000000000c6bcc221a71b1bc297b346d041188eba6377fd21a934f3a3e should not display any fiat value).

This goes the other way too: if you change network from testnet/signet to mainnet, the fiat value is not displayed until a page refresh: 

<img width="1119" alt="Screenshot 2024-03-01 at 11 19 51" src="https://github.com/mempool/mempool/assets/46578910/8d40164e-5db9-4ad5-9989-b40e151ca8d4">

**Comment by natsoni** [comment] 2024-03-18 04:50
Can't reproduce the issue on prod anymore, I guess this was probably fixed in #4747

**Closed** 2024-03-21 03:08 UTC
Labels: bug
