### ISSUE TITLE
Difficulty adjusment issues

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#3569] opened 2023-03-25 02:04 UTC
Using regtest, I've noticed few issues with the difficulty adjustment. While it's regtest, those issues most likely applies to mainnet/testnet/signet as well.

- APIs (rest + websocket) and the frontend does not show the same number of `remaining blocks`
  - `"remainingBlocks": 2`
  - <img width="272" alt="Screenshot 2023-03-25 at 10 55 24" src="https://user-images.githubusercontent.com/9780671/227680041-89add82c-c7ca-4fb3-8720-0bc3da9d0f0d.png">
  
- What is the difference between `1 block remaining` and `next block`?
  - <img width="272" alt="Screenshot 2023-03-25 at 10 55 24" src="https://user-images.githubusercontent.com/9780671/227680132-01aac01e-cf1e-4d58-a363-2b1ad5ba5bee.png">
  - <img width="257" alt="Screenshot 2023-03-25 at 10 55 43" src="https://user-images.githubusercontent.com/9780671/227680141-f4e080c5-69a1-42df-a493-5dc18252c8a9.png">
  - Note that the tooltip does not resize properly when we show `next block`

- Once the difficulty epoch is completed, I honestly don't know what's going on. Why do we show `2 blocks expected` ? I would also expect the progress bar to fully reset instead of being fully green. If that's normal, probably need a FAQ.
  - <img width="623" alt="Screenshot 2023-03-25 at 10 56 19" src="https://user-images.githubusercontent.com/9780671/227680202-d0a3aeea-7f7e-4637-9f60-a4a4ca18899d.png">
  
- When we start a new difficulty epoch, the estimated date is broken because it seems we send `null`
  - <img width="561" alt="image" src="https://user-images.githubusercontent.com/9780671/227682212-a089e8af-5149-41fc-a352-7272dafe7b31.png">

- In `difficulty-adjustment.ts`, we compute `let timeAvgSecs = diffSeconds / blocksInEpoch;` which lead to `INFINITY` when there is no block yet in the current difficulty epoch. This leads to some value being nullified in the API response (not expected as per the interface definition). This probably also break testnet difficulty adjustment.

**Comment by mononaut** [comment] 2023-03-25 23:41
> APIs (rest + websocket) and the frontend does not show the same number of remaining blocks

"Remaining blocks" in the API response/websocket is the number of blocks remaining until the difficulty adjustment occurs (i.e. until the first block of the *next* epoch)

"Remaining blocks" in the frontend is "the number of blocks remaining in *this* epoch"

So it's expected that they're one block different.

It's a bit awkward, but I didn't want to make a breaking change to semantics of the API response.

**Comment by mononaut** [comment] 2023-03-25 23:42
> What is the difference between 1 block remaining and next block?

The "Next block" tooltip is for the flashing white pixel, which represents the next block to be mined.

"N block(s) remaining" is the tooltip for the unmined and unexpected blocks remaining in the current epoch (i.e. the dark gray pixels).

We should never show a "1 block remaining" tooltip, because the flashing white "Next block" takes priority - I'm not sure why it appeared for you, and I can't reproduce it.

**Comment by mononaut** [comment] 2023-03-25 23:42
> Note that the tooltip does not resize properly when we show next block

This is semi-intentional, to prevent the tooltip from jumping around too much when it's clamped to the right hand side of the screen.

**Comment by mononaut** [comment] 2023-03-25 23:43
> Once the difficulty epoch is completed, I honestly don't know what's going on. Why do we show 2 blocks expected ? I would also expect the progress bar to fully reset instead of being fully green. If that's normal, probably need a FAQ.

Yes, this is expected. The progress bar resets on the first block of the next epoch, not the last block of the current epoch.

"2 blocks expected" presumably because it was about 20 minutes since your last difficulty adjustment when you took the screenshot - so we expected 2 blocks to be mined in that time, but you've actually mined 2016 blocks, which puts you 2014 blocks ahead of schedule. This is illustrated in the progress bar by 2 blue "mined + expected" pixels, and 2014 green "mined ahead of schedule" pixels.

**Comment by mononaut** [comment] 2023-03-25 23:44
> When we start a new difficulty epoch, the estimated date is broken because it seems we send null
> ...
> In difficulty-adjustment.ts, we compute let timeAvgSecs = diffSeconds / blocksInEpoch; which lead to INFINITY when there is no block yet in the current difficulty epoch. This leads to some value being nullified in the API response (not expected as per the interface definition). This probably also break testnet difficulty adjustment.

Yep, I'm fixing these now.

**Comment by nymkappa** [comment] 2023-03-26 01:21
> > Once the difficulty epoch is completed, I honestly don't know what's going on. Why do we show 2 blocks expected ? I would also expect the progress bar to fully reset instead of being fully green. If that's normal, probably need a FAQ.
> 
> Yes, this is expected. The progress bar resets on the first block of the next epoch, not the last block of the current epoch.
> 
> "2 blocks expected" presumably because it was about 20 minutes since your last difficulty adjustment when you took the screenshot - so we expected 2 blocks to be mined in that time, but you've actually mined 2016 blocks, which puts you 2014 blocks ahead of schedule. This is illustrated in the progress bar by 2 blue "mined + expected" pixels, and 2014 green "mined ahead of schedule" pixels.

Should not the bar reset when when the last block the current epoch is mined? I would expect an empty bar while we're waiting for the first block the epoch to be mined. We would show the empty bar and the blinking white pixel.

**Comment by nymkappa** [comment] 2023-03-26 01:41
> > Note that the tooltip does not resize properly when we show next block
> 
> This is semi-intentional, to prevent the tooltip from jumping around too much when it's clamped to the right hand side of the screen.

We need to iterate a bit more on this 👍🏻

**Comment by nymkappa** [comment] 2023-03-26 02:13
> > What is the difference between 1 block remaining and next block?
> 
> The "Next block" tooltip is for the flashing white pixel, which represents the next block to be mined.
> 
> "N block(s) remaining" is the tooltip for the unmined and unexpected blocks remaining in the current epoch (i.e. the dark gray pixels).
> 
> We should never show a "1 block remaining" tooltip, because the flashing white "Next block" takes priority - I'm not sure why it appeared for you, and I can't reproduce it.

I think it only appears if the tooltip is already showing when a new block arrives. Mouse the mouse out and in again shows the `next block` text properly.

**Comment by softsimon** [comment] 2023-03-27 06:18
fixed in https://github.com/mempool/mempool/pull/3576

**Closed by softsimon** 2023-03-27 06:18 UTC
