### ISSUE TITLE
Filtering not working on https://mempool.space/graphs/mempool

### ISSUE THREAD

**Issue by jogc** [mempool/mempool#3807] opened 2023-05-26 11:18 UTC
### Description

The filtering function on the Graphs page does not do anything. Regardless of what levels I disable, the graph is not updated. It worked just 1-2 weeks ago. Have tried three different web browsers.

#### Version

Current version on mempool.space

### Steps to reproduce

Go to https://mempool.space/graphs/mempool#2h
Click the filter button
Select for example 40-50

### Expected behaviour

I expect all transactions below 40-50 sat/vb to disappear from the graph

### Actual behaviour

The graph remains the same

#### Device or machine

Tried Firefox and Chrome on Linux, Safari on iOS

**Comment by nymkappa** [comment] 2023-05-26 21:41
Duplicate of https://github.com/mempool/mempool/issues/3790
Fixed in https://github.com/mempool/mempool/pull/3780

**Closed by nymkappa** 2023-05-26 21:41 UTC
