### ISSUE TITLE
High Memory Consumption

### ISSUE THREAD

**Issue by Cristian-Bejan** [mempool/mempool#600] opened 2021-06-30 17:59 UTC
I noticed today that mempool.space consumed a lot of memory in Chrome Version 91.0.4472.114 (Official Build) (64-bit) for Windows - around 4GB. It's not the first time and seems to happen independent of the Chrome version and when the tab has been opened for a long time. A refresh fixes the issue.
![Mempool-Memory](https://user-images.githubusercontent.com/60579945/124008951-af7ee800-d9e5-11eb-965b-882f9563acb0.PNG)

**Comment by wiz** [comment] 2021-06-30 18:38
yeah... this memory leak is a long-standing issue that I believe got introduced when we made a change to the chart library for inverting it - IIRC when disabling the charts on the dashboard it doesn't reproduce

**Comment by Cristian-Bejan** [comment] 2021-06-30 18:47
Thanks for clarifying that @wiz . Didn't notice that it's possible to disable charts. Nice! Learning something everyday 😎

**Comment by wiz** [comment] 2021-07-03 15:03
@knorrium has been working hard on this investigation and found many leaks so far in the chart library

**Comment by softsimon** [comment] 2021-07-04 03:03
Yes, the legacy chart library is most likely to blame. It was the cause last time I investigated this.

We are planning to replace the library in the next version update so will start working on it soon. #94

**Comment by wiz** [comment] 2021-09-04 19:01
Fixed by #755

**Closed by wiz** 2021-09-04 19:01 UTC
Labels: bug
