### ISSUE TITLE
Address page can show transactions out of order

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#770] opened 2021-09-08 07:12 UTC
https://mempool.space/address/19bVqRfiC4s51fEMd3ogk1PPzoBT3ZyyUm

The two transactions at the address above are out of order, we can see the one with the most confirmations first.

![9247BFFE-1A92-4D92-8E57-CB636BEB73E5](https://user-images.githubusercontent.com/100320/132463016-ab10e5c5-4411-4e91-b3f8-d36500ea7ab4.jpeg)

**Comment by softsimon** [comment] 2021-09-08 07:56
What backend are you running? Esplora or romanz/electrs with bitcoind?

Possible duplicate of https://github.com/mempool/mempool/issues/424

**Comment by knorrium** [comment] 2021-09-08 08:14
@softsimon both, you can repro in prod or on an Umbrel node. The example above has two txs in two different blocks mined at the same time, while the original issue has two txs within the same block.

**Comment by softsimon** [comment] 2021-09-08 14:05
> https://mempool.space/address/19bVqRfiC4s51fEMd3ogk1PPzoBT3ZyyUm
> 
> The two transactions at the address above are out of order, we can see the one with the most confirmations first.

Ok, I found the cause of this bug. We are sorting the transactions by block time, and in this case, the newer block had a older block time than the previous block. So the solution should be to firstly sort by block height and secondly by block time.

**Closed** 2021-09-26 19:04 UTC
Labels: bug
