### ISSUE TITLE
Add support for Bech32 bc1 addresses being case-insensitive

### ISSUE THREAD

**Issue by GlenCooper** [mempool/mempool#301] opened 2021-01-19 05:39 UTC
### Description

Bech32 (Segwit) bitcoin addresses are case-insensitive, per https://archive.vn/tzxCb#selection-909.18-909.92
The search box should accommodate for this, but does not currently.

### Steps to reproduce

Search on example address "BC1Q0QFZUGE7VR5S2XKCZRJKCCMXEMLYYN8MHX298V".

### Expected behaviour

Should match "bc1q0qfzuge7vr5s2xkczrjkccmxemlyyn8mhx298v" and show results.

### Actual behaviour

Tool does NOTHING, not even an error(?!).

### Screenshots

![Screenshot from 2021-01-19 05-31-47](https://user-images.githubusercontent.com/967793/104991974-e05ef800-5a17-11eb-811c-8fb10bea01c7.png)

#### Device or machine

Ubuntu 20.04, Firefox

**Comment by softsimon** [comment] 2021-01-19 06:02
Thanks for your bug report. Fix will be included next time we upgrade the website.

**Comment by GlenCooper** [comment] 2021-01-25 21:10
Confirmed that it works properly now.  Thanks!

**Comment by SamSamskies** [comment] 2021-08-17 18:14
@softsimon the website does not seem to work with uppercase Bech32 addresses right now. Has there been a regression?

**Comment by softsimon** [comment] 2021-08-17 18:42
Seems like it.

**Comment by softsimon** [comment] 2021-08-29 00:12
> @softsimon the website does not seem to work with uppercase Bech32 addresses right now. Has there been a regression?

Tested now and it does work. Can you confirm that it's not working?

<img width="508" alt="Screen Shot 2021-08-29 at 03 11 57" src="https://user-images.githubusercontent.com/8561090/131234068-31f4be26-e65f-41e3-8a80-a608a2160ce1.png">

**Comment by SamSamskies** [comment] 2021-08-29 00:53
It works when you hit return key now, but clicking the search icon still doesn't do anything.

**Comment by wiz** [comment] 2021-09-01 16:43
Re-opening due to fix being reverted

**Closed** 2021-09-07 21:36 UTC

**Comment by GlenCooper** [comment] 2021-09-27 03:03
Thanks for fixing this (again).

**Comment by softsimon** [comment] 2021-09-27 08:42
> Thanks for fixing this (again).

Thanks for reporting bugs and keep it up 👍
