### ISSUE TITLE
Fee span is incorrect

### ISSUE THREAD

**Issue by dscotese** [mempool/mempool#101] opened 2020-08-10 03:38 UTC
### Description
This image shows three numbers (circled in red) that indicate that the fee span displayed in the graphic representation of block 643018 at the top of the page shows a low of 15, while the fee on the second-to-last page of transactions for that block is only 5.  There appears to be a miscalculation somewhere, which led me to believe my transaction wasn't included.

### Version
The version used on mempool.space around 8:20pm PDT, August 9, 2020. Neither the commit id nor a version number is displayed anywhere on the About page (another issue I will add in a moment).

### Expected behaviour
I expect the lower number in the fee span display to be close to the fee rate of the Tx with the lowest fee in the block.  Skipping the lowest 10 or 20 makes sense, but the last ten pages of transactions in this block, as displayed by mempool.space, all have fee rates lower than 15 sat/vB.

### Actual behaviour
The fee span's low end is higher than all fee rates on the last ten pages of transactions in the block.

### Screenshots
![image](https://user-images.githubusercontent.com/1767796/89749884-80ceea80-da7e-11ea-9135-3e1bddd5f98e.png)

#### Device or machine

Windows 10 laptop running Brave browser.

**Comment by softsimon** [comment] 2020-08-12 19:43
We're considering reverting the fix for this bug. Because it was actually intended before.

The reasoning is to give the user information about what was the minimum fee that was required to get into the block, that's why we cut away the extremes, which usually is 1sat/vB CPFP transactions.

If you compare the two different versions here, you can see that on the top with the "fix" shows 1 and 3 sat/vB, but it isn't that useful information when almost all blocks are going to have 1 sat/vB.

The blocks below has removed those and show to the users that 102 and 126 sat/vB was the minimum fee required to get into the block.

<img width="323" alt="Screenshot 2020-08-13 at 02 32 17" src="https://user-images.githubusercontent.com/8561090/90059947-23e96380-dd0e-11ea-8af1-3339fa97d76b.png">

Do you have any input to this @dscotese ?

**Comment by wiz** [comment] 2020-08-12 19:44
@dscotese Simon and I discussed your bug report on our call today. I'm going to re-open this issue to start the discussion. Basically I think we should revert this fix because there are 2 fees for every transaction, and most people don't know about the 2nd fee calculation, which is only done by miners using the `getblocktemplate` RPC call of BItcoin Core (or their own implementation if they're rolling their own). Basically miners will calculate the average fee for an entire unconfirmed mempool chain of CPFP transactions and use that to optimize fees in their block, and if you had thought about that fee you wouldn't have been mislead. The span that mempool displays is actually a guide for users to use for fee calculation. Obviously any miner could even include zero fee TX in their mined block, so displaying the true fee span isn't very useful if the lower number is always 1 or something, because using 1 sat/vByte for a new TX wouldn't get confirmed.

**Comment by dscotese** [comment] 2020-08-13 06:15
I agree with your suggestion. If it isn't too much trouble, transactions which are spent by other transactions in the block could be eliminated from the list of transactions from which fees are taken.  This removes the decrease in fee range that results from including the parent transactions that have those low fees, and provides the range of fees pertinent to independent transactions.  Another way to do it is to find the highest fee still in the mempool after removing from it all the transactions in the current block, but that probably requires changes to the bitcoin client itself and not just mempool.space code.

**Comment by softsimon** [comment] 2020-08-13 06:21
> If it isn't too much trouble, transactions which are spent by other transactions in the block could be eliminated from the list of transactions from which fees are taken.

Yep, this is how the behavior basically was at the time of your issue report :) But I do understand it's confusing when at the same time finding lower fee transactions in the transactions list.

**Comment by dscotese** [comment] 2020-08-13 21:45
This would help: Put an asterisk at the end of every fee span, and at the bottom of the page, add a note:
* Fee span only accounts for _independent_ transactions. Many low-fee transactions are included because a child transaction increased their effective fee, so we filter those out.
My philosophy is **never** to hide information just because it might be complicated.  Rather, work out a good explanation and move it to areas at which only the curious and interested will look.

**Comment by wiz** [comment] 2021-04-19 15:12
Fixed by #395

**Closed by wiz** 2021-04-19 15:12 UTC
Labels: bug
