### ISSUE TITLE
Esplora backend does not work with HTTP

### ISSUE THREAD

**Issue by jobeirne-nydig** [mempool/mempool#4724] opened 2024-02-29 16:56 UTC
When using `mempool/electrs` along with `mempool/backend` in a docker-compose configuration (e.g. https://gist.github.com/jobeirne-nydig/4c907fcb4d3508a2767867aa4e360aec), the following logs appear in the `mempool/backend` container:

```
Attaching to api-1
api-1  | wait-for-it.sh: waiting 720 seconds for mempool-db:3306
api-1  | wait-for-it.sh: mempool-db:3306 is available after 0 seconds
api-1  | Feb 29 16:32:53 [135] NOTICE: Starting Mempool Server... (cd5a510)
api-1  | Feb 29 16:32:53 [135] INFO: Database connection established.
api-1  | Feb 29 16:32:53 [135] DEBUG: MIGRATIONS: Running migrations
api-1  | Feb 29 16:32:53 [135] DEBUG: MIGRATIONS: Database engine version '10.5.21-MariaDB-1:10.5.21+maria~ubu2004'
api-1  | Feb 29 16:32:53 [135] DEBUG: MIGRATIONS: Current state.schema_version 66
api-1  | Feb 29 16:32:53 [135] DEBUG: MIGRATIONS: Latest DatabaseMigration.version is 66
api-1  | Feb 29 16:32:53 [135] DEBUG: MIGRATIONS: Nothing to do.
api-1  | Feb 29 16:32:53 [135] DEBUG: pools-v2.json sha | Current: a2325375e5a4aca0878fa2909d219d365bb0077b | Github: a2325375e5a4aca0878fa2909d219d365bb0077b
api-1  | Feb 29 16:32:53 [135] INFO: Starting statistics service
api-1  | Feb 29 16:32:53 [135] ERR: Cannot get fetch orphaned blocks. Reason: connect ECONNREFUSED 172.20.0.5:8332
api-1  | Feb 29 16:32:53 [135] NOTICE: Mempool Server is running on port 8999
api-1  | Feb 29 16:32:53 [135] DEBUG: updateMempoolInfo: connect ECONNREFUSED 172.20.0.5:8332
api-1  | Feb 29 16:32:53 [135] WARN: esplora request failed undefined null/mempool/txids
api-1  | Feb 29 16:32:53 [135] WARN: connect ENOENT null
api-1  | Feb 29 16:32:53 [135] DEBUG: Exception in runMainUpdateLoop() (count: 1). Retrying in 1 sec. Reason: connect ENOENT null. Stack trace: Error: connect ENOENT null
api-1  |     at AxiosError.from (/backend/package/node_modules/axios/dist/node/axios.cjs:837:14)
api-1  |     at RedirectableRequest.handleRequestError (/backend/package/node_modules/axios/dist/node/axios.cjs:3083:25)
api-1  |     at RedirectableRequest.emit (node:events:526:35)
api-1  |     at eventHandlers.<computed> (/backend/package/node_modules/follow-redirects/index.js:14:24)
api-1  |     at ClientRequest.emit (node:events:514:28)
api-1  |     at Socket.socketErrorListener (node:_http_client:495:9)
api-1  |     at Socket.emit (node:events:514:28)
api-1  |     at emitErrorNT (node:internal/streams/destroy:151:8)
api-1  |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
api-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
api-1  | Feb 29 16:32:53 [135] DEBUG: AxiosError: connect ENOENT null
api-1  | Feb 29 16:32:53 [135] DEBUG: [Mining] Inserted 0 MtGox USD weekly price history into db
api-1  | Feb 29 16:32:54 [135] DEBUG: updateMempoolInfo: connect ECONNREFUSED 172.20.0.5:8332
api-1  | Feb 29 16:32:54 [135] WARN: esplora request failed undefined null/mempool/txids
api-1  | Feb 29 16:32:54 [135] WARN: connect ENOENT null
```

Note the line `esplora request failed undefined null/mempool/txids`. This would suggest to me that something proximate to this code (https://github.com/mempool/mempool/blob/018d4230e2f11e1ca1a31c42f6ef032331123368/backend/src/api/bitcoin/esplora-api.ts#L47) is not working correctly.

I see that in the mempool production config, you guys are using a unix socket in lieu of the HTTP server.

**Comment by mononaut** [comment] 2024-02-29 18:12
This is caused by a bug in the docker backend start script.

It looks like it's already been fixed in https://github.com/mempool/mempool/pull/4523, so I suppose we just need to push a new docker tag? cc @knorrium @wiz

**Comment by knorrium** [comment] 2024-03-01 01:50
We are planning a small patch release and could include that fix.

**Comment by wiz** [comment] 2024-03-01 02:06
sorry but mempool/electrs is only compatible with mempool 3.x
for mempool 2.x you need to use blockstream/electrs or romanz/electrs

**Closed by wiz** 2024-03-01 02:06 UTC

**Comment by jobeirne-nydig** [comment] 2024-03-01 16:06
Happy to use whichever version of mempool alongside `mempool/electrs`, there just doesn't seem to be an easy way to do that with docker images that are currently released.

**Comment by wiz** [comment] 2024-03-05 15:34
if you're running mempool 3.x then you probably want romanz/electrs which is available for docker.
mempool/electrs isn't available for docker other than CI/regtest usage.
